name: Go
on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        name: "Coverage"
        ignoreForks: false
        status: "error"
        description: "Test coverage: TEST"
